build:
  image: plugins/drone-git
  commands:
    - true
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ryane/drone-docker-test
    tag:
      - latest
    when:
      event: tag
